version: '3.1'
services:
    nginx:
        # 镜像名称
        image: xxl6097/go-raspberry:0.0.2
        # 容器名字
        container_name: go-raspberry
        # 开机自动重启
        restart: always
        # 端口号绑定（宿主机:容器内）
        ports:
            - '3002:8080'
        environment:
            - PUID=0
            - PGID=0
            - UMASK=022
        # 目录映射（宿主机:容器内）
        volumes:
           - ./conf:/app/conf


#拷贝容器conf文件到物理机
#docker cp go-raspberry:/app/conf .
